# This is a basic workflow to help you get started with Actions

name: DITA-GARAGE

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build HTML5 + Bootstrap
        uses: jason-fox/dita-build-action@master
        with:
          install: |
            apt-get update -q
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
            apt-get install -y apt-utils
            dita install https://github.com/mmclhugo1/DITA-plugins/archive/main.zip
          build: dita -i garage.ditamap -o out -f html5-bootstrap -v
      - name: Upload DITA
        uses: actions/upload-artifact@v2
        with:
          name: dita-artifact
          path: 'out'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: latest # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
