on:
    pull_request:
      branches: [main]
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: gh-actions
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'PR opened :rocket:'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: PR-BOT
        SLACK_FOOTER: Powered by PR-BOT
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
